### PR TITLE
Add support for /nix/ volume within the container

### PR DESCRIPTION
**Pull request by FedX-sudo**
I have been messing around with Distrobox, and one issue I discovered was it did not mount /nix/ in the container which is needed for NixOS and systems with Nix. I therefore quickly added that feature, and support for NixOS is a lot better. Thank you again for all the work that has gone into this!

### CODE REVIEW

**Comment by 89luca89** [comment]
Thanks @FedX-sudo 
I was wondering tho what will happen with this Mount if we create a nix distrobox on a nix host?
Will this create problems?

**Comment by FedX-sudo** [comment]
Now that I think about it, yeah, that probably would, in which case, it would also create problems if Nix was installed on the system in general.

**Comment by FedX-sudo** [comment]
So I should probably have it set up more like: 
```
if [ -d /nix/ ] && ![ echo $container_image | grep "nix" ] && ![ echo $container_name | grep "nix"]; then 
```

**Comment by 89luca89** [comment]
We could move the thing in the init
And check if /nix does not exist inside the container, you could link it to /run/host/nix?

**Comment by FedX-sudo** [comment]
It would have to be on /nix because stuff is symbolically linked to /nix, and without that directory in that path it kind of just plain breaks on NixOS.

**Comment by 89luca89** [comment]
> It would have to be on /nix because stuff is symbolically linked to /nix, and without that directory in that path it kind of just plain breaks on NixOS.

Yes you could check if /nix already exist in the container (in which case let's just skip to not break stuff)
If not exists, we can bind Mount /run/host/nix to /nix in the container, that should work right?

**Comment by FedX-sudo** [comment]
I don't see why not. That is going to be one crazy chain of mounts and links...

**Comment by 89luca89** [comment]
> I don't see why not. That is going to be one crazy chain of mounts and links...

Absolutely :joy: 
But what things are not working if /nix is not present in the container?
Trying to understand what  does this mount fix

**Comment by FedX-sudo** [comment]
On NixOS that is where all the binaries are stored. Everything is symlinked from /nix/store, and some config stuff from /nix/var, so if /nix does not exist, none of the NixOS binaries exist...

**Comment by FedX-sudo** [comment]
Actually, this may be a non-issue. I was testing NixOS to see how it would break, and it looks like it's breaking for completely unrelated reasons.

**Comment by 89luca89** [comment]
> On NixOS that is where all the binaries are stored. Everything is symlinked from /nix/store, and some config stuff from /nix/var, so if /nix does not exist, none of the NixOS binaries exist...

Makes sense
Then the support in init approach should be doable 
In the end bindmounting in the init is not that different from doing that in the --volume phase

**Comment by 89luca89** [comment]
> Actually, this may be a non-issue. I was testing NixOS to see how it would break, and it looks like it's breaking for completely unrelated reasons.

Probably the mount would fix the issue of usinf stuff in tour ~/.nix directory nothing more right?

**Comment by FedX-sudo** [comment]
> > Actually, this may be a non-issue. I was testing NixOS to see how it would break, and it looks like it's breaking for completely unrelated reasons.
> 
> Probably the mount would fix the issue of usinf stuff in tour ~/.nix directory nothing more right?


No, I reverted that change to test and ran it verbose and got this error: 
```
++ podman --log-level debug logs -t --since 2022-01-29T09:19:07.891457283-07:00 nixos
+ container_manager_log='2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
2022-01-29T09:19:08.212317000-07:00 Error: An error occurred'
+ case "${container_manager_log}" in
+ printf '%s\n' '2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
2022-01-29T09:19:08.212317000-07:00 Error: An error occurred'
2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
2022-01-29T09:19:08.212317000-07:00 Error: An error occurred
```

**Comment by 89luca89** [comment]
> > > Actually, this may be a non-issue. I was testing NixOS to see how it would break, and it looks like it's breaking for completely unrelated reasons.
> > 
> > 
> > Probably the mount would fix the issue of usinf stuff in tour ~/.nix directory nothing more right?
> 
> No, I reverted that change to test and ran it verbose and got this error:
> 
> ```
> ++ podman --log-level debug logs -t --since 2022-01-29T09:19:07.891457283-07:00 nixos
> + container_manager_log='2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
> 2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
> 2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
> 2022-01-29T09:19:08.212317000-07:00 Error: An error occurred'
> + case "${container_manager_log}" in
> + printf '%s\n' '2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
> 2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
> 2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
> 2022-01-29T09:19:08.212317000-07:00 Error: An error occurred'
> 2022-01-29T09:19:08.207913000-07:00 /root/.nix-profile/bin/find
> 2022-01-29T09:19:08.210838000-07:00 Error: could not find a supported package manager.
> 2022-01-29T09:19:08.211919000-07:00 Error: could not set up base dependencies.
> 2022-01-29T09:19:08.212317000-07:00 Error: An error occurred
> ```

This is with normal distrobox, nix host and what type of container?

**Comment by FedX-sudo** [comment]
Nixos from docker.io/nixos/nix:latest.

**Comment by FedX-sudo** [comment]
Also not a NixOS host specific issue, I have the exact same error on Fedora35 host.

**Comment by 89luca89** [comment]
Ahaha completely forgot that nix container are not supported in the first place 😅

**Comment by FedX-sudo** [comment]
So I assume this branch is ready to merge then?

**Comment by 89luca89** [comment]
Yep sorry was AFK :smile: 

I don't see in the foreseeable future support for nix docker images as there is not way to just support them in the init.
If in the future the situation changes, we can move it to the init aswell

Merging.

**Comment by FedX-sudo** [comment]
Awesome! Thank you! 

Also, Nix has it's own unprivileged container system thing. Maybe point users looking for NixOS over there?

**Comment by 89luca89** [comment]
Can you inform me better on this? I'm completely new to the nix world :sweat_smile: 
You could open a PR to point it in the readme if you want

**Comment by FedX-sudo** [comment]
Yeah totally! Nix is... unique to say the least.

**Comment by 89luca89** [comment]
It's something I'll need to try seriously in my life :sweat_smile: But for now immutable/ostree distros are just a lot more appealing to me

**Comment by FedX-sudo** [comment]
Totally, coming from MacOS I was looking for the freedom to mess around on root however I wanted, so I can't say ostree stuff is super appealing to me, but I do like the idea, and /nix/store is immutible so it strikes a rather nice balence in my opinion.

**Comment by 89luca89** [comment]
At which point I just think... why not...

image

**Comment by FedX-sudo** [comment]
Absolutely. I probably should try Kinoite, just add it to the list with LFS...

**Pull request merged**
