### PR TITLE
Add --hostname argument and DBX_CONTAINER_HOSTNAME env var

### PR DESCRIPTION
**Pull request by sandorex**
I thought it would require more changes but its already passed to podman so why not have it as an option when it requires so little work

### CODE REVIEW

**Comment by sandorex** [comment]
This would also remove the need for `--init-hooks 'echo "$(uname -n)" > /etc/hostname'` hacks which while they do kinda work they dont set the env var `HOSTNAME` and require more hacks on top of it

**Comment by 89luca89** [comment]
That's a good idea @sandorex thanks!

Can you also adjust the documentation in `docs/usage` and the entry in `useful_tips`? 
Thanks!

**Comment by sandorex** [comment]
> Can you also adjust the documentation in docs/usage and the entry in useful_tips?

Sure ill look into it now

**Comment by sandorex** [comment]
I have not updated the shell autocompletions cause frankly it looks like magic

**Comment by 89luca89** [comment]
Autocompletion works with the `--help` so that should already be sorted :)

**Comment by 89luca89** [comment]
Thanks a lot @sandorex ! :heart:

**Pull request merged**
