### PR TITLE
host exec docs: 755 -> 644 

### PR DESCRIPTION
**Pull request by misobarisic**
I changed the environment variable prefix in `export`. `DISTROBOX` -> `DBX` to match other project files.

Also removed `x` permissions wise from host-exec docs.

### CODE REVIEW

**Comment by 89luca89** [comment]
Thanks @misobarisic 

Not sure how I feel about those changes of variable names
For two main reasons:

1 - those are not meant to be configurable, those are stuff inected in the env by `create`, so keeping them separate from the rest could be useful
2 - this is a breaking change, to take effect people will need to re-create their containers

**Comment by misobarisic** [comment]
Alright then, sounds good. Thanks for the heads up.

**Comment by misobarisic** [comment]
Repurposed the PR to just be a permission change for the host exec docs

**Comment by 89luca89** [comment]
Cool thanks!

**Pull request merged**
