### PR TITLE
export: Add call to update-desktop-database tool

### PR DESCRIPTION
**Pull request by luc14n0**
That's important to ensure exported applications will show up in whatever the user/DE is using desktop files for (taskbars, desktop menus, etc) right after exportation.

Desktop Environments should already install `update-desktop-database` by default - that's how they handle packages installing `.desktop` files. I'd believe that most Window Managers should also have it.

### CODE REVIEW

**Comment by 89luca89** [comment]
Thanks @luc14n0 

If we add a base dependency we need to add it to the `init` also

Instead of this, I was thinking we probably want to update the host's desktop-database
So instead of this maybe we can do this:

`	/usr/bin/distrobox-host-exec --yes update-desktop-database -q 2> /dev/null || :`

So this will either force-update the desktop-db on the host, or fail silently if the host doesn't have the tool

**Comment by luc14n0** [comment]
> Instead of this, I was thinking we probably want to update the host's desktop-database

Duh, my bad.

> So instead of this maybe we can do this:
> 
> `	/usr/bin/distrobox-host-exec --yes update-desktop-database -q 2> /dev/null || :`
> 
> So this will either force-update the desktop-db on the host, or fail silently if the host doesn't have the tool

Sounds good to me.

**Comment by 89luca89** [comment]
Added the fix quickly and merging :) 

Thanks a lot!

**Comment by luc14n0** [comment]
Sure thing. Thanks for the amendment.

**Pull request merged**
