### PR TITLE
create: Makefile

### PR DESCRIPTION
**Pull request by misobarisic**
I've created a simple Makefile for people who prefer using `make` to install their software. Right now it is just a _fancy_ `install` and `uninstall` wrapper.

### CODE REVIEW

**Comment by M0Rf30** [comment]
Never used a `make` command with a `PREFIX`. 
A common usage variable is DESTDIR for the fakeroot, but PREFIX, "in a Makefile world" is always used by the `./configure` or `cmake` configuration previous stage. Nobody forbid you to use this solution. just speaking freely...

**Comment by 89luca89** [comment]
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

Maybe DESTDIR works better

**Comment by 89luca89** [comment]
Hey @misobarisic are you stil working on this?

**Comment by misobarisic** [comment]
I was just thinking about closing the PR since I didn't do anything.

**Comment by 89luca89** [comment]
No problem, if you feel like working on it again just open a new one :+1: thanks!

**Pull request closed without merging**
