### PR TITLE
Add init and pre-init hook defaults as supported config options

### LINKED ISSUE #497: [Error] --pre-init-hooks doesn't match --init-hooks screwing up .distroboxrc config
**Describe the bug**
Using `--pre-init-hooks` on the `distrobox create` command line sets the `container_pre_init_hook` variable to `--pre-init-hooks=${2}`, while using `--init-hooks` sets `container_init_hook` to `${2}`.
Both of these hooks can be set in the distroboxrc file with their appropriate variables, but one requires to you manually add the docker/podman command-line switch to it as well and the other doesn't.

**To Reproduce**
Examine https://github.com/89luca89/distrobox/blob/main/distrobox-create#L296

**Expected behavior**
The `--pre-init-hook=` part should be prepended in code right before it's used on [line 633](https://github.com/89luca89/distrobox/blob/main/distrobox-create#L633) rather than added during command-line argument parsing.

### PR DESCRIPTION
**Pull request by mtalexan**
Since the `--init-hook` and `--pre-init-hook` are the current method for resolving custom TLS certificates being needed by corporate proxies (see #493), being able to configure fixed hooks that don't need to be manually added on the command-line each time are useful.  

The variables already existed and could be overridden by the config files (which are just sourced into the scripts), but the `--pre-init-hook` was processed strangely and was appending the arguments needed when calling docker at argument parsing-time instead (see #497).  The command-line options override the config file options already, so no changes were needed for that.

Unrelated, but there was a typo in the `bashate` command in the CONTRIBUTING guide as well. 

/closes #497

### CODE REVIEW

**Comment by 89luca89** [comment]
Hi @mtalexan 

seems all ok for me, did a couple of changes so we can handle the variable as a normal one, but seems all ok
Will wait for the CI to finish and will merge if all ok :+1: 

Thanks a lot!

**Comment by mtalexan** [comment]
Seems reasonable to me, supporting blank argument for the `pre-init-hook` in `distrobox-init` so that it can be blindly passed as part of `distrobox-create`s call to it.  

I don't follow what the GitHub workflow changes are, it looks like there's some outside generation step you ran and then reference as the new config?

**Comment by 89luca89** [comment]
> Seems reasonable to me, supporting blank argument for the `pre-init-hook` in `distrobox-init` so that it can be blindly passed as part of `distrobox-create`s call to it.

Yep :+1: 

> I don't follow what the GitHub workflow changes are, it looks like there's some outside generation step you ran and then reference as the new config?

No it's just GH has deprecated some stuff and the CI was not going ahead so I just fixed this now :shrug:

**Comment by 89luca89** [comment]
Merged, thanks a lot!

**Pull request merged**
