### PR TITLE
Add home prefix

### PR DESCRIPTION
**Pull request by misobarisic**
I've added the ability to use a home prefix. An equivalent to defining a custom `/home` partition. Does not have precedence over custom homes set with `--home`.

If a home directory, either created with `--home` or `--prefix`, does not exist, it will be created.

### CODE REVIEW

**Comment by 89luca89** [comment]
Hey @misobarisic 

I'm not sure of this, in which way this is different than simply specifying `--home/-H`?

**Comment by misobarisic** [comment]
It is a directory where all container homes would live. Instead of specifying `--home` for every box explicitly, it would automatically be bound to one if the environment variable was set. Think of it as `/home/user` where `home` is the prefix and `user` the container name.

**Comment by misobarisic** [comment]
@89luca89 I agree. Now that I think about it, having a flag for a specific prefix is redundant. It should depend on environment variables instead.

**Comment by 89luca89** [comment]
Cool

At this point I'd document this a bit better inside the `usage` of `create` and maybe an entry in `useful_tips` so we've covered the feature :smile:

**Comment by misobarisic** [comment]
Should these autogenerated home directories be removed when the container gets deleted by `distrobox-rm`?

**Comment by 89luca89** [comment]
> Should these autogenerated home directories be removed when the container gets deleted by `distrobox-rm`?

Yea was thinking of it
I'd say, we should ask confirmation (following the behaviour with `-f` and `--yes` flags obviously)

**Comment by misobarisic** [comment]
> > Should these autogenerated home directories be removed when the container gets deleted by `distrobox-rm`?
> 
> Yea was thinking of it I'd say, we should ask confirmation (following the behaviour with `-f` and `--yes` flags obviously)

I'm also thinking about prompting for confirmation to delete the home dir of containers which use `--home`. Easier implementation too. Just checking if the container home differs from the host.

**Comment by 89luca89** [comment]
> > > Should these autogenerated home directories be removed when the container gets deleted by `distrobox-rm`?
> > 
> > 
> > Yea was thinking of it I'd say, we should ask confirmation (following the behaviour with `-f` and `--yes` flags obviously)
> 
> I'm also thinking about prompting for confirmation to delete the home dir of containers which use `--home`. Easier implementation too. Just checking if the container home differs from the host.

Agree!

**Comment by misobarisic** [comment]
I've added an environment variable `DBX_CONTAINER_RM_CUSTOM_HOME` which is responsible for autodeleting the custom home of containers.

Interactive sessions ask for confirmation when `DBX_CONTAINER_RM_CUSTOM_HOME` or `--rm-home` haven't been specified.
Non interactive sessions delete only when either of the two have been specified and are _truthy_.

**Comment by misobarisic** [comment]
@89luca89 is something blocking the merge as of now?

**Pull request merged**
