### PR TITLE
Add clickable links to images in README.md

### PR DESCRIPTION
**Pull request by ryleu**
I left the original link alone (other than wrapping it in \`) so that it's still easy to select, copy, and paste into the terminal.

I added a hyperlinked :link: emoji so that people can easily "just click it" because some people like to do that.

I also fixed the very strange whitespace. Are you using a monospace font?

### CODE REVIEW

**Comment by 89luca89** [comment]
Hey thanks a lot for your contribution!

Yea I use monospace fonts as I edit in the terminal (vim) :smiley: 

Before merging I'd like to adjust the links to point to the dockerhub page as right now they will all 404 as those are meant for podman/docker only to download

**Comment by ryleu** [comment]
> Before merging I'd like to adjust the links to point to the dockerhub page as right now they will all 404 as those are meant for podman/docker only to download

Oh, whoops! I didn't think to double check all of the links, sorry about that!

**Comment by 89luca89** [comment]
Absolutely no problem!

I'd say:

- all `https://docker.io/` become `https://hub.docker.com/`
- all `library/` become `_/` 
- removing the :tag in the end
- the fedora registry link become all: https://registry.fedoraproject.org/repo/fedora-toolbox/tags/ as there is no way to link to specific tags
- the oracle linux link becomes this [MONSTER](https://container-registry.oracle.com/ords/f?p=113:4:4776583827114:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:1,1,Oracle%20Linux,Oracle%20Linux,1,0&cs=3kBjJdoAei1PEG6VSGXCvLauCia79wak2Ja7EXaI_VElWRMoo1saeLCg_WfUD30RnyAYlbkoJnnBuD8xvj2fq_g)
- the opensuse registry link becomes https://build.opensuse.org/project/show/openSUSE:Containers:Tumbleweed and https://build.opensuse.org/project/show/openSUSE:Containers:Leap
- the quay links become https://quay.io/repository 

In general we need to drop the tags from the links as they are not supported, so for example all centos, debian, ubuntu, fedora links are all the same!

**Comment by ryleu** [comment]
I'll work on this after school today. I'll let you know once I finish it.

**Comment by ryleu** [comment]
Now that I've used it a bit more, I have realized that this PR is not useful, so I'm going to close it and make a new one that *just* fixes the white space once I get around to it.

**Pull request closed without merging**
