### PR TITLE
FIx fail on installation dirs not existing

### PR DESCRIPTION
**Pull request by pepa65**

### CODE REVIEW

**Comment by nathanchance** [comment]
`install -D` should take care of creating `dest_path` and `man_dest_path` if they do not exist. What is the failure you are seeing?

**Comment by misobarisic** [comment]
Please elaborate on the failing condition. As previously said, `install -D` should take care of creating the directory. Are you, for some reason, missing the `install` coreutil?

**Comment by pepa65** [comment]
> As previously said, `install -D` should take care of creating the directory.
Sorry, I did not use -D. On the other hand, why not just always create missing directories? I was going off this: https://distrowatch.com/weekly.php?issue=current#distrobox
But if the code already is creating the directories, I am sorry for the noise, and please disregard this pull.

**Comment by misobarisic** [comment]
> > As previously said, `install -D` should take care of creating the directory.
> > Sorry, I did not use -D. On the other hand, why not just always create missing directories? I was going off this: https://distrowatch.com/weekly.php?issue=current#distrobox
> > But if the code already is creating the directories, I am sorry for the noise, and please disregard this pull.

The install script has been changed since the publishing of distrowatch's article. One notable change is #180.

**Pull request closed without merging**
