### PR TITLE
fix:[#1500] allow users to exclude files when using --nvidia

### LINKED ISSUE #1500: [Error] Nvidia integration mounts files as read-only that prevent installing some packages inside the container.
**Describe the bug**
I found this problem when trying to install the `libboost1.74-dev` package in a Ubuntu 22.04 container with a Ubuntu 24.04 host created with nvidia integration (`--nvidia` flag). 

When creating a container with the `--nvidia` flag, [distrobox-init](https://github.com/89luca89/distrobox/blob/4c38d6b3f9bc833e58a435471158935824727805/distrobox-init#L1856-L1877) will mount as read-only all files under /usr/ that have "nvidia" in the name.

In my case, I had the `libboost1.83-dev` package installed in the host (Ubuntu 24.04), which installs some header files under `/usr/include/boost/...` with the string "nvidia" in the file name, that are unrelated to the nvidia driver or libraries. The problem appears in the container (Ubuntu 22.04) if I try to install boost (libboost1.74-dev), because it will try to overwrite those header files that were mounted as read-only. This is the error from apt:

```shell
Unpacking libboost1.74-dev:amd64 (1.74.0-14ubuntu3) ...
dpkg: error processing archive /tmp/apt-dpkg-install-Zcdiwt/18-libboost1.74-dev_1.74.0-14ubuntu3_amd64.deb (--unpack):
unable to make backup link of './usr/include/boost/compute/detail/nvidia_compute_capability.hpp' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```

I believe those files should not be mounted in the container, even if they have "nvidia" in the file name.

It is possible to pass an option to dpkg to ignore those files, but this is not a solution, because the files installed in the host and the container are from different versions of boost.

**To Reproduce**
1. [Prerequisite] Have a host distro with boost installed. I only tested this with Ubuntu 24.04 in the host and 22.04 in the container, but it should be possible to replicate it with other distros.
2. Create a new box with Nvidia integration:
```shell
distrobox create --image docker.io/library/ubuntu:22.04 --name boost_test --nvidia
```
3. Try to install boost libraries inside the container:
```shell
distrobox enter boost_test
apt install -y libboost1.74-dev
```

It should not be possible to install because of files mounted by `distrobox-init`.

**Expected behavior**
When using the `--nvidia` flag, the files unrelated to the nvidia driver / libraries should not be mounted in the container.

It should be possible to install boost in the container, even if boost is already installed in the host. This issue might also happen with different packages (not only boost) if they have any file with "nvidia" in the file name.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Which version or podman, docker or lilipod?
 **podman 4.9.3**
 - Which version of distrobox?
 **1.7.0**
 - Which host distribution?
 **Ubuntu 24.04**
 - How did you install distrobox?
 **From Ubuntu's universe repository through apt.**

**Additional context**
I am aware of issue #1054, but this is different, as I am not trying to install cuda or other Nvidia library, just the boost libraries. I think it might not be a good idea to mount all files that are found with "nvidia" in the name, but I have zero idea about the best way to solve this.

### PR DESCRIPTION
**Pull request by ToolmanP**
Resolve #1500

### CODE REVIEW

**Comment by maalsolami** [comment]
You may need to set a default value for ```nvidia_exclusion```  in the defaults section of create (L#57-85) in case the flag is not used to avoid ``` nvidia_exclusion: parameter not set``` error and ensure that it works only when the ```--nvidia``` option is set.
I was able to use it successfully to create a container with Nvidia integration and install ROS noetic in it, which was not possible before due to this error:
```
dpkg: error processing archive /var/cache/apt/archives/cmake-data_3.16.3-1ubuntu1.20.04.1_all.deb (--unpack):
 unable to make backup link of './usr/share/cmake-3.16/Modules/Compiler/NVIDIA-CUDA.cmake' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb ...
Unpacking libboost1.71-dev:amd64 (1.71.0-6ubuntu6) ...
dpkg: error processing archive /var/cache/apt/archives/libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb (--unpack):
 unable to make backup link of './usr/include/boost/compute/detail/nvidia_compute_capability.hpp' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/cmake-data_3.16.3-1ubuntu1.20.04.1_all.deb
 /var/cache/apt/archives/libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ToolmanP** [comment]
> You may need to set a default value for `nvidia_exclusion` in the defaults section of create (L#57-85) in case the flag is not used to avoid ` nvidia_exclusion: parameter not set` error and ensure that it works only when the `--nvidia` option is set. I was able to use it successfully to create a container with Nvidia integration and install ROS noetic in it, which was not possible before due to this error:
> 
> ```
> dpkg: error processing archive /var/cache/apt/archives/cmake-data_3.16.3-1ubuntu1.20.04.1_all.deb (--unpack):
>  unable to make backup link of './usr/share/cmake-3.16/Modules/Compiler/NVIDIA-CUDA.cmake' before installing new version: Invalid cross-device link
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> Preparing to unpack .../libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb ...
> Unpacking libboost1.71-dev:amd64 (1.71.0-6ubuntu6) ...
> dpkg: error processing archive /var/cache/apt/archives/libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb (--unpack):
>  unable to make backup link of './usr/include/boost/compute/detail/nvidia_compute_capability.hpp' before installing new version: Invalid cross-device link
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> Errors were encountered while processing:
>  /var/cache/apt/archives/cmake-data_3.16.3-1ubuntu1.20.04.1_all.deb
>  /var/cache/apt/archives/libboost1.71-dev_1.71.0-6ubuntu6_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

yeah my bad i fix this issue

**Comment by 89luca89** [comment]
I agree with @mirkobrombin 
we need to improve the detection, not adding more and more obscure flags

we should investigate what and why things break

**Comment by 89luca89** [comment]
Closing this, did a fix

**Pull request closed without merging**
