### PR TITLE
New website

### PR DESCRIPTION
**Pull request by daudix-UFO**
Initial work on improving website experience, now website uses [os-component-website](https://github.com/jimmac/os-component-website) as a template for nicer look

Preview available at [daudix-ufo.github.io/distrobox](https://daudix-ufo.github.io/distrobox)

### CODE REVIEW

**Comment by 89luca89** [comment]
Hi @daudix-UFO 
that looks great! :fire: 

Just a couple of things

- markdownlint is failing, can you fix the markdown?
- can we use the big logo instead of the GIF? I'd like it more

Thanks!

**Comment by daudix-UFO** [comment]
Sure, will fix those!

**Comment by daudix-UFO** [comment]
Alright, I think all markdown issues are fixed, and pixel are gif are replaced with big logo

_markdownlint are sooo annoying sometimes xD_

**Comment by 89luca89** [comment]
Great suff thanks :smile: 
Really appreciate your help on this!

Thanks a lot!

**Comment by 89luca89** [comment]
The website will be up with the new release
As the github pages are pointing to the release and not to `main`, just to inform you @daudix-UFO

**Comment by daudix-UFO** [comment]
Ah okay, I thought why it doesn't update :laughing:

**Pull request merged**
