### PR TITLE
Create Manuals

### PR DESCRIPTION
**Pull request by misobarisic**
I've created a man directory where command manpages would be located. These files should also be copied upon installation.
I've updated the script to reflect that as well.
The `-p` parameter no longer would point to `/usr/local/bin` but instead `/usr/local`. It would just be a prefix to `bin` and `share/man`.

This is just a conceptual commit and PR so far.
Preview:
image

### CODE REVIEW

**Comment by 89luca89** [comment]
Great idea! Thanks :smile: 

When it's done we can then simply point the `show_help()` to `man distrobox-$COMMAND` so we can also tidy up a bit the code :smile:

**Comment by 89luca89** [comment]
> I am not so sure if `show_help()` needs to point to `man distrobox-$COMMAND`. So far I have not seen a project take that approach. But you have got a point. It would tidy the code up just a tiny bit.

It's a way to centralize the docs anyway 😄

**Comment by misobarisic** [comment]
I've converted a manual page to md and placed it in the GitHub pages directory which can be previewed [here](https://misobarisic.github.io/distrobox/distrobox-create).
The question is should we generate these pages using git pre-commit script or by making a GitHub action?

**Comment by 89luca89** [comment]
> I've converted a manual page to md and placed it in the GitHub pages directory which can be previewed [here](https://misobarisic.github.io/distrobox/distrobox-create). The question is should we generate these pages using git pre-commit script or by making a GitHub action?

Mmmh I think best way should be a GH action yes

**Comment by misobarisic** [comment]
I decided on using the git pre-commit hook to avoid using unnecessary commits for converting man pages to markdown (in docs).

**Comment by 89luca89** [comment]
> I decided on using the git pre-commit hook to avoid using unnecessary commits for converting man pages to markdown (in docs).

What are you using to do this? We could integrate it in the gh-pages pipeline to auto-generate it :+1:

**Comment by misobarisic** [comment]
> > I decided on using the git pre-commit hook to avoid using unnecessary commits for converting man pages to markdown (in docs).
> 
> What are you using to do this? We could integrate it in the gh-pages pipeline to auto-generate it +1

The gen script is located [here](https://github.com/misobarisic/distrobox/blob/man_pages/man/genmd). It depends on pandoc when it comes to converting man pages to markdown.

**Comment by misobarisic** [comment]
How do we integrate it into the gh-pages pipeline? I am not really familiar when it comes to that.

**Comment by 89luca89** [comment]
> How do we integrate it into the gh-pages pipeline? I am not really familiar when it comes to that.

If you invite me to your repo misobarisic/distrobox I can commit to it and we can work on this PR together :smile:

**Comment by misobarisic** [comment]
> If you invite me to your repo misobarisic/distrobox

Done.

**Comment by 89luca89** [comment]
Cool I'll play with the GH action in some free time :smile:

**Comment by 89luca89** [comment]
I was thinking
what about the reverse?

We maintain the docs as source of truth and generate the man pages from the markdown?

https://spin.atomicobject.com/2015/05/06/man-pages-in-markdown-ronn/

**Comment by misobarisic** [comment]
We could do that. It's easier to maintain. We just need to decide which program to use since I've tried pandoc and it returned improperly formatted files

**Comment by 89luca89** [comment]
I'll do some experiments :+1:

**Comment by 89luca89** [comment]
So i've experimented with `ronn` https://github.com/rtomayko/ronn and I'm very satisfied with the unification of man pages and markdown.
I'm not overly worried about automating this process right now, it's quite easy (thanks to the gen script) and I'm the one who does releases anyway :smile: 

I'm pushing on this branch what I've come up with ron and the new generated pages, let me know if you spot something not ok
If all is ok I'm going to merge :smile:

**Comment by 89luca89** [comment]
Seems like it's all ok I'm going to merge, in case we can open a new issue to automate it in the future
for now it's plenty of improvements :smile:

**Pull request merged**
