### PR TITLE
Add license header and SPDX-License-Identifier

### PR DESCRIPTION
**Pull request by alcir**
I'm not a lawyer, but IMHO a license header in each script looks more professional :sweat_smile: and maybe in line with some policy.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
The FSF and I agree with you. https://github.com/89luca89/distrobox/blob/7a51438b6fa6e6a24d5ce86fa8734dd9de4d4343/LICENSE#L629-L648

**Review by TheEvilSkeleton — APPROVED** [review]
The FSF and I agree with you. https://github.com/89luca89/distrobox/blob/7a51438b6fa6e6a24d5ce86fa8734dd9de4d4343/LICENSE#L629-L648

**Review by TheEvilSkeleton — COMMENTED** [review]
I suggest moving the LICENSE file to COPYING because the FSF recommends so: https://www.gnu.org/licenses/gpl-howto.en.html. Perhaps even use the [Markdown](https://www.gnu.org/licenses/gpl-3.0.md) format to make it far more readable than RAW.

**Comment by 89luca89** [comment]
Oh, nice I like the markdown format of the license 😄 

I was also wondering about how to maintain the copyright present but general enough to cover the contributors, I think this solution works well I like it 👍

**Comment by TheEvilSkeleton** [comment]
> I was also wondering about how to maintain the copyright present but general enough to cover the contributors, I think this solution works well I like it +1

Yup. Either way, "2021" implies "or later", so it doesn't have to be constantly updated.

**Comment by 89luca89** [comment]
> > I was also wondering about how to maintain the copyright present but general enough to cover the contributors, I think this solution works well I like it +1
> 
> Yup. Either way, "2021" implies "or later", so it doesn't have to be constantly updated.

I was referring to the copyright owners, having it as " distrobox contributors" should be general enough to not have problems with contributions copyright

**Comment by 89luca89** [comment]
@alcir should be done by last commit right?

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
I suggest moving LICENSE to COPYING (or even Markdown version).

**Comment by 89luca89** [comment]
> I suggest moving LICENSE to COPYING (or even Markdown version).

So we remove the LICENSE file, and put [THIS](https://www.gnu.org/licenses/gpl-3.0.md) in it's place?

**Comment by TheEvilSkeleton** [comment]
Yup, and call it `COPYING.md`. So it's `LICENSE` -> `COPYING.md`.

**Comment by 89luca89** [comment]
Cool, let's keep this PR for the license headers, I'll do that change in the `main` directly

**Comment by 89luca89** [comment]
Implemented :+1:

**Review by TheEvilSkeleton — APPROVED** [review]

**Pull request merged**
