### PR TITLE
Typo fix?

### PR DESCRIPTION
**Pull request by misobarisic**

### CODE REVIEW

**Comment by alegrey91** [comment]
@89luca89 you are definitely not able to write "distro" 😁

**Comment by 89luca89** [comment]
@alegrey91 ahaha the typos are part of my own being

@misobarisic thanks a lot!

**Comment by misobarisic** [comment]
@89luca89 More README typos means more time spent on actual code, right? Right?!?

**Comment by 89luca89** [comment]
@misobarisic  absolutely

Or just that I have fat fingers.

Or both.
 ¯\_(ツ)_/¯

**Pull request merged**
