### PR TITLE
init: explicit version for opensuse

### LINKED ISSUE #149: [openSUSE] Latest Leap image not working
**Describe the bug**
Installing openSUSE Leap inside a container doesn't work as the latest official repository (Leap 15.4) does not contain `libvte-2`.

**To Reproduce**
Create a distrobox container with the opensuse/leap:latest image.

**Expected behavior**
To get a working container.

**Logs**
`2022-01-29T18:32:45.294405000+01:00 /usr/bin/mount
2022-01-29T18:32:45.294630000+01:00 /usr/bin/passwd
2022-01-29T18:32:45.297444000+01:00 /usr/bin/zypper
2022-01-29T18:32:50.290437000+01:00 Retrieving repository 'Update repository of openSUSE Backports' metadata [.....done]
2022-01-29T18:32:51.810810000+01:00 Building repository 'Update repository of openSUSE Backports' cache [....done]
2022-01-29T18:32:53.645893000+01:00 Retrieving repository 'Non-OSS Repository' metadata [...done]
2022-01-29T18:32:53.679699000+01:00 Building repository 'Non-OSS Repository' cache [....done]
2022-01-29T18:33:36.923921000+01:00 Retrieving repository 'Main Repository' metadata [....................................done]
2022-01-29T18:33:55.930871000+01:00 Building repository 'Main Repository' cache [....done]
2022-01-29T18:34:49.375880000+01:00 Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata [.....................................................done]
2022-01-29T18:35:08.626774000+01:00 Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache [....done]
2022-01-29T18:35:13.035674000+01:00 Retrieving repository 'Main Update Repository' metadata [......done]
2022-01-29T18:35:13.884585000+01:00 Building repository 'Main Update Repository' cache [....done]
2022-01-29T18:35:16.822742000+01:00 Retrieving repository 'Update Repository (Non-Oss)' metadata [...done]
2022-01-29T18:35:16.847008000+01:00 Building repository 'Update Repository (Non-Oss)' cache [....done]
2022-01-29T18:35:16.847450000+01:00 Loading repository data...
2022-01-29T18:35:18.394402000+01:00 Reading installed packages...
2022-01-29T18:35:20.984143000+01:00 'shadow' is already installed.
2022-01-29T18:35:20.985056000+01:00 No update candidate for 'shadow-4.8.1-2.43.x86_64'. The highest available version is already installed.
2022-01-29T18:35:20.985328000+01:00 'util-linux' is already installed.
2022-01-29T18:35:20.985470000+01:00 No update candidate for 'util-linux-2.36.2-4.5.1.x86_64'. The highest available version is already installed.
2022-01-29T18:35:20.985550000+01:00 'procps' is already installed.
2022-01-29T18:35:20.985629000+01:00 No update candidate for 'procps-3.3.15-7.19.1.x86_64'. The highest available version is already installed.
2022-01-29T18:35:20.985705000+01:00 'findutils' is already installed.
2022-01-29T18:35:20.985779000+01:00 No update candidate for 'findutils-4.8.0-1.20.x86_64'. The highest available version is already installed.
2022-01-29T18:35:20.985860000+01:00 'ncurses' not found in package names. Trying capabilities.
2022-01-29T18:35:20.985936000+01:00 'libncurses6' providing 'ncurses' is already installed.
2022-01-29T18:35:20.986011000+01:00 'libvte-2' not found in package names. Trying capabilities.
2022-01-29T18:35:21.017526000+01:00 Error: An error occurred`

**Desktop (please complete the following information):**
 - Arch Linux

### PR DESCRIPTION
**Pull request by misobarisic**
Resolves #149. 

Fixed by changing the `libvte-2` package.

Tested on tumbleweed and leap (15.4 and 15.2).

### CODE REVIEW

**Comment by 89luca89** [comment]
Hey @misobarisic sorry I didn't see the open PR and pushed a fix already :sweat_smile: 

I've used a star glob because I see that on older versions it might be _90 or in future it can change to _92

**Comment by misobarisic** [comment]
> I've used a star glob because I see that on older versions it might be _90 or in future it can change to _92

That's good

**Comment by 89luca89** [comment]
Let's close this, sorry again for not viewing this earlier!

**Comment by misobarisic** [comment]
@89luca89 no worries. Your approach was even better.

**Pull request closed without merging**
