### PR TITLE
zsh completions: fixed issue with some arguments having invalid syntax

### PR DESCRIPTION
**Pull request by fredricocalamari**
Fixed issue where the completions were showing invalid syntax ex. '--additional-flags' and a few others were being incorrectly completed as '--additional-flags='

### CODE REVIEW

**Comment by 89luca89** [comment]
Thanks a lot @fredricocalamari !

Seeing that you're a zsh user, can I ask you if you can help with the installation path of zsh autocompletion? Regarding #1213

**Comment by onurmercury** [comment]
I'm sure now it is $prefix/share/zsh/site-functions

for e.g.
https://build.opensuse.org/package/view_file/shells:zsh-users:zsh-completions/zsh-completions/zsh-completions.spec?expand=1

https://github.com/NixOS/nixpkgs/blob/711b0df6923c889ebb7d6deced2c76a2f41b445f/pkgs/shells/zsh/zsh-completions/default.nix#L16

**Comment by fredricocalamari** [comment]
> I'm sure now it is $prefix/share/zsh/site-functions
> 
> for e.g. https://build.opensuse.org/package/view_file/shells:zsh-users:zsh-completions/zsh-completions/zsh-completions.spec?expand=1
> 
> https://github.com/NixOS/nixpkgs/blob/711b0df6923c889ebb7d6deced2c76a2f41b445f/pkgs/shells/zsh/zsh-completions/default.nix#L16

those work too, it's up to your preference

**Comment by 89luca89** [comment]
Thanks everyone for the info!

And thanks @fredricocalamari for the fixes!

**Pull request merged**
