### PR TITLE
feat: New logotype

### PR DESCRIPTION
**Pull request by daudix-UFO**
Brand-new brand for the Distrobox. Current logo is nice, but not as scalable (e.g it's not suitable for favicon), so this is my take at creating full set of branding assets with unique logotype and some extras

The idea behind the logo: _Run any distro on same cube_. Rubic's cube can have a huge amount of possible color variations on same cube, just as distrobox giving ability to run any distro on same _cube_.

distrobox-logo-guidelines

### CODE REVIEW

**Comment by 89luca89** [comment]
Hi @daudix-UFO thanks a lot for all of this work! :smile: 

Personally I'm a bit attached to the old logo like this:

distrobox-logo-small

and this:

distrobox-logo-round

@j4ckr3d is the original author

Maybe we can find a way to reuse the pink/purple box thing?

**Comment by daudix-UFO** [comment]
Originally I wanted to make the logo use purple color, but to remove unwanted miss-taking distrobox with toolbox and to have good contrast on black/white backgrounds I have choose blue. But anyway, I can try making something with the pink/blue colors )

**Comment by 89luca89** [comment]
> Originally I wanted to make the logo use purple color, but to remove unwanted miss-taking distrobox with toolbox and to have good contrast on black/white backgrounds I have choose blue. But anyway, I can try making something with the pink/blue colors )

Heh yes pink/purple is a bit hard to contrast
But I was thinking that the scheme is also quite engraved as identity in distrobox itself so I'd like to keep it in-theme

So mainly some sort of way to apply that "effect" to your box icon maybe?
Like merging the old logo and the new one :) 

Let's also see what @j4ckr3d thinks :)

**Comment by daudix-UFO** [comment]
Something like this, tho it will not work in smaller sizes and monochrome/inverted variant

изображение

**Comment by 89luca89** [comment]
> Something like this, tho it will not work in smaller sizes and monochrome/inverted variants
> 
> изображение

I like it more tho :joy: 
You can tell I'm not a designer :eyes: 

Anyway for mono-chrome we could go for a "non-fuzzy" version, that would make sense

**Comment by daudix-UFO** [comment]
> But I was thinking that the scheme is also quite engraved as identity in distrobox itself so I'd like to keep it in-theme

I don't think that new logo will affect identity of distrobox a lot. currently the only place the logo present in is the README header, and it's not present in other places. The logo will likely be used with text most of the time, so identifying "what is this" should not be a problem

изображение

For example, Flathub had a [brand refresh](https://blog.jimmac.eu/2023/flathub-brand-refresh) recently, opinions were different, but to the end of the day, people seem to be OK about it

About the pink/blue glitch, I understand why you like it :smile: it look cool in places like big README header with dark background, but looking at it from 1 meter distance or on phone makes it look quite fuzzy, so this will be tricky one

I will work on the alt versions, hopefully we will get the "this one looks just right!" design :wink:

**Comment by 89luca89** [comment]
Thanks a lot @daudix-UFO !

I know it's not easy guessing stranger's tastes :joy:

**Comment by mirkobrombin** [comment]
The logo is very well done, and I like how it's paired with the font. My two cents: I'm against yet another brand with blue tones, and I agree with Luca in preserving the purple. I did some contrast checks, and `#6A1B9A` seems to surpass them all. I think it fits well with white text. Additionally, I wonder if a dice with terminals as faces is too cliché.

image

**Comment by 89luca89** [comment]
Thanks @mirkobrombin ! That's what I was thinking
We could find a couple of shades to use for light/dark backgrounds and use those as base palette

**Comment by daudix-UFO** [comment]
Hi @mirkobrombin, yup, I'm not a fan of having yet-another blue logo too, the color you provided is awesome! I'm gonna change the assets to it asap. about the dice with terminal faces, honestly don't know, it supposed to be rubic's cube angle piece but seems like it's not super obvious :sweat_smile:

**Comment by daudix-UFO** [comment]
The new palette

изображение

**Comment by mirkobrombin** [comment]
> Hi @mirkobrombin, yup, I'm not a fan of having yet-another blue logo too, the color you provided is awesome! I'm gonna change the assets to it asap. about the dice with terminal faces, honestly don't know, it supposed to be rubic's cube angle piece but seems like it's not super obvious sweat_smile

not obvious for me :D

> The new palette
> 
> изображение

looks very good to me!

**Comment by 89luca89** [comment]
> The new palette
> 
> изображение

Yes! Really like it! :heart:

**Comment by daudix-UFO** [comment]
Updated the logo to use the new palette

**Comment by daudix-UFO** [comment]
Let's summarize what we have right now and how it looks in the "wild"

**Comment by mirkobrombin** [comment]
Looks good to me

**Comment by 89luca89** [comment]
Thanks @daudix-UFO !

I was thinking the main "pagelogo" cube would be better if inverted maybe?
Like purple cube with white ">_" instead of the other way around?

**Comment by daudix-UFO** [comment]
Hm, let's see

**Comment by daudix-UFO** [comment]
Снимок экрана от 2023-03-19 20-32-18
Снимок экрана от 2023-03-19 20-33-07

**Comment by daudix-UFO** [comment]
Yeah, like this logo have more color and solves the barely visible ">_"

**Comment by 89luca89** [comment]
Nice, what about having a full colored cube? 
Having the "frame" of the box inverted with the background (either white/black or vice versa) like the ">_" and make the cube purple instead of transparent

**Comment by j4ckr3d** [comment]
Hi @daudix-UFO 
That's a great design, i like it a lot!
I would prefer a fixed black background in the little terminals on the box instead of transparent ones, just to be consistent, what do you think? 

Anyway, great job!

**Comment by daudix-UFO** [comment]
> Nice, what about having a full colored cube? Having the "frame" of the box inverted with the background (either white/black or vice versa) like the ">_" and make the cube purple instead of transparent

The dark variant looks ok, but the light one looks like downgrade

Снимок экрана от 2023-03-19 20-58-21
Снимок экрана от 2023-03-19 21-00-02

**Comment by 89luca89** [comment]
> > Nice, what about having a full colored cube? Having the "frame" of the box inverted with the background (either white/black or vice versa) like the ">_" and make the cube purple instead of transparent
> 
> The dark variant looks ok, but the light one looks like downgrade
> 
> Снимок экрана от 2023-03-19 20-58-21 Снимок экрана от 2023-03-19 21-00-02

what if we don't use pure black for the light variant? either a light gray or maybe we could do borders/>_ in dark purple, and the filling in light purple?

**Comment by j4ckr3d** [comment]
@daudix-UFO yeah the dark one is way cooler but the lighter one doesn't feel right...
Could we also try with other colors like orange or green? maybe even on a less punchy tone
Or maybe using a black/white frame and just getting a color accent on the ">_"
What do you think about that?

**Comment by daudix-UFO** [comment]
> > > Nice, what about having a full colored cube? Having the "frame" of the box inverted with the background (either white/black or vice versa) like the ">_" and make the cube purple instead of transparent
> > 
> > 
> > The dark variant looks ok, but the light one looks like downgrade
> > Снимок экрана от 2023-03-19 20-58-21 Снимок экрана от 2023-03-19 21-00-02
> 
> what if we don't use pure black for the light variant? either a light gray or maybe we could do borders/>_ in dark purple, and the filling in light purple?

None of this will have good contrast

**Comment by mirkobrombin** [comment]
As we are still discussing, I did two mockups, one using a similar [plantation](https://chir.ag/projects/name-that-color/#265A53) palette:

image

and another using a similar [armadillo](https://chir.ag/projects/name-that-color/#4B413A) palette:

image

In both, the cube's faces are filled with a almost-inversion of the primary color.

**Comment by daudix-UFO** [comment]
Wooow, this looks super clean! I like it a lot

**Comment by 89luca89** [comment]
Thanks @mirkobrombin 

As I was discussing with you and @j4ckr3d we might have to abandon the purple for various reasons

For now we've found these two palettes, maybe we can experiment a bit?
At this point I'm trying to choose between those two :joy:  

Green seems to be the more "balanced" one, but the dark/mocha is my preferred
The light mocha seems  a bit too muted maybe? Being the principal logo of a project, being of muted/forgettable colors seems counter-productive :man_shrugging:

**Comment by mirkobrombin** [comment]
I have no preferences between the two so I keep neutral. I understand what you mean but I think it's subjective, for example I believe that the armadillo variant is more iconic for how the two shades of color contrast.

**Comment by j4ckr3d** [comment]
Those both looks amazing.
For me the absolute winner is the green one, @89luca89 already know that, but as @mirkobrombin said the other variant could be iconic, it's hard to see similiar colorscheme outside Groovbox 
@89luca89 last choice is yours 🤷🏻

**Comment by 89luca89** [comment]
I think i'd like to give a shot to the mocha/armadillo scheme :smile: 
I'd like to see the assets in that scheme to evaluate better

**Comment by daudix-UFO** [comment]
Okay, gonna make a brand-book with this color to see how it looks ;)

**Comment by daudix-UFO** [comment]
Alright, here is quick thingy

distrobox-logo-guidelines

**Comment by pietrodicaprio** [comment]
Yo, my two cents: I would go for the green ("planation") palette rather for the mohca (armadillo) one. The darker logo looks also older while the green one is more fresh.

**Comment by mirkobrombin** [comment]
> Alright, here is quick thingy (palette is shamelessly taken from mirkobrombin :P)

I love it!

**Comment by daudix-UFO** [comment]
Here is one with plantation palette

distrobox-logo-guidelines-plantation

**Comment by pietrodicaprio** [comment]
it's up to @89luca89 👀

**Comment by 89luca89** [comment]
Thanks everyone for the suggestions and support!

@daudix-UFO I think I'll go for armadillo. I like the idea that the boxes are... well the color of a box :eyes:

Do you think we can take some inspiration from the gruvbox color palette? https://github.com/gruvbox-community/gruvbox
It's my preferred colorscheme in vim also :joy:  and I see the armadillo palette can be somewhat compatible with some of those colors?

**Comment by daudix-UFO** [comment]
We can create custom palette similar to gruvbox ;)

**Comment by 89luca89** [comment]
> Or we can use gruvbox

We could try, the idea is to have a final result similar to the armadillo logo but maybe we can reuse the other colors in some accents and in other graphics? (just guessing I'm a complete ignorant of design :joy: )

I think the main repo for the color palette is this one: https://github.com/gruvbox-community/gruvbox-contrib

**Comment by mirkobrombin** [comment]
`bg3` and `fg2` looks good in both light and dark variants

**Comment by daudix-UFO** [comment]
Hm, looks pretty

image

**Comment by daudix-UFO** [comment]
With `fg` and `bg`

image

**Comment by mirkobrombin** [comment]
Mh not sure about that

**Comment by daudix-UFO** [comment]
test

**Comment by 89luca89** [comment]
@daudix-UFO 
Mmmh probably it was better before
Maybe we can use some of the other colors (maybe the darker-purple or the orange) for underline?

Like instead of "CUBE Distrobox" we have CUBE Distro**box** (box underlined)

**Comment by daudix-UFO** [comment]
@89luca89 "before" is purple box with white `>_`?

**Comment by 89luca89** [comment]
> Alright, here is quick thingy (palette is shamelessly taken from mirkobrombin :P)
> 
> distrobox-logo-guidelines

No meaning this, sorry

**Comment by daudix-UFO** [comment]
Quick draft, I like the direction

image

**Comment by daudix-UFO** [comment]
And a few variants with completely different colors

image
Снимок экрана от 2023-03-22 21-48-41

**Comment by mirkobrombin** [comment]
I think all those are visually too complex

**Comment by 89luca89** [comment]
> Alright, here is quick thingy (palette is shamelessly taken from mirkobrombin :P)
> 
> distrobox-logo-guidelines

Thanks @daudix-UFO 
I think in the end I'll just go for this, it's simpler and leaner

**Comment by daudix-UFO** [comment]
okay, gonna update assets soon

**Comment by daudix-UFO** [comment]
Done! Armadillo is the new Purple!

**Comment by 89luca89** [comment]
Thanks a lot @daudix-UFO!
Just a question, why in the pdf the license is referring to Toolbx? Is the logo derived from their project in some ways?

**Comment by daudix-UFO** [comment]
Ah, I used toolbx brand book as a base, will remove it

**Comment by 89luca89** [comment]
> Ah, I used toolbx brand book as a base, will remove it

ah no it's ok for me, it was just to know, maybe we can add a link to the original one just to be sure to credit properly :+1:

**Comment by daudix-UFO** [comment]
ah, I got it wrong :facepalm: I thought I have left old metadata :P I can add link to the toolbox website, there you can download press kit

**Comment by 89luca89** [comment]
> ah, I got it wrong facepalm I thought I have left old metadata :P I can add link to the [toolbox website](https://containertoolbx.org), there you can download press kit

Sure, a direct link to the original source (like the proper download link) will be better if possible

**Comment by daudix-UFO** [comment]
I guess the link will be too long

`https://github.com/containers/containertoolbx.org/blob/main/assets/logo/toolbx-logo-specimen.svg`

maybe this could work?

Снимок экрана от 2023-03-23 01-22-47

**Comment by 89luca89** [comment]
@daudix-UFO let me know when you think we can merge
So I can also go trough the docs and change icons/banners :)

**Comment by 89luca89** [comment]
Thanks a lot @daudix-UFO for the work!
Merging it!

**Pull request merged**
